//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "ConnectionManeuverAssist.h"

static int
memb_regional_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1LL && size <= 4LL)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_regional_constr_7 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1l,  4l }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_regional_constr_7 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1l,  4l }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_regional_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RegionalExtension_92P33,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_regional_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_regional_specs_7 = {
	sizeof(struct ConnectionManeuverAssist__regional),
	offsetof(struct ConnectionManeuverAssist__regional, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_regional_7 = {
	"regional",
	"regional",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	SEQUENCE_OF_decode_aper,
	SEQUENCE_OF_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_regional_tags_7,
	sizeof(asn_DEF_regional_tags_7)
		/sizeof(asn_DEF_regional_tags_7[0]) - 1, /* 1 */
	asn_DEF_regional_tags_7,	/* Same as above */
	sizeof(asn_DEF_regional_tags_7)
		/sizeof(asn_DEF_regional_tags_7[0]), /* 2 */
	&asn_PER_type_regional_constr_7,
	asn_MBR_regional_7,
	1,	/* Single element */
	&asn_SPC_regional_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ConnectionManeuverAssist_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectionManeuverAssist, connectionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneConnectionID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"connectionID"
		},
	{ ATF_POINTER, 5, offsetof(struct ConnectionManeuverAssist, queueLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ZoneLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"queueLength"
		},
	{ ATF_POINTER, 4, offsetof(struct ConnectionManeuverAssist, availableStorageLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ZoneLength,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"availableStorageLength"
		},
	{ ATF_POINTER, 3, offsetof(struct ConnectionManeuverAssist, waitOnStop),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WaitOnStopline,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"waitOnStop"
		},
	{ ATF_POINTER, 2, offsetof(struct ConnectionManeuverAssist, pedBicycleDetect),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PedestrianBicycleDetect,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pedBicycleDetect"
		},
	{ ATF_POINTER, 1, offsetof(struct ConnectionManeuverAssist, regional),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_regional_7,
		memb_regional_constraint_1,
		&asn_PER_memb_regional_constr_7,
		0,
		"regional"
		},
};
static const int asn_MAP_ConnectionManeuverAssist_oms_1[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ConnectionManeuverAssist_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConnectionManeuverAssist_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* connectionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* queueLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* availableStorageLength */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* waitOnStop */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pedBicycleDetect */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* regional */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConnectionManeuverAssist_specs_1 = {
	sizeof(struct ConnectionManeuverAssist),
	offsetof(struct ConnectionManeuverAssist, _asn_ctx),
	asn_MAP_ConnectionManeuverAssist_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ConnectionManeuverAssist_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ConnectionManeuverAssist = {
	"ConnectionManeuverAssist",
	"ConnectionManeuverAssist",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ConnectionManeuverAssist_tags_1,
	sizeof(asn_DEF_ConnectionManeuverAssist_tags_1)
		/sizeof(asn_DEF_ConnectionManeuverAssist_tags_1[0]), /* 1 */
	asn_DEF_ConnectionManeuverAssist_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConnectionManeuverAssist_tags_1)
		/sizeof(asn_DEF_ConnectionManeuverAssist_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ConnectionManeuverAssist_1,
	6,	/* Elements count */
	&asn_SPC_ConnectionManeuverAssist_specs_1	/* Additional specs */
};

