//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "DataParameters.h"

static int check_permitted_alphabet_2(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127LL)) return -1;
	}
	return 0;
}

static int check_permitted_alphabet_3(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127LL)) return -1;
	}
	return 0;
}

static int check_permitted_alphabet_4(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127LL)) return -1;
	}
	return 0;
}

static int check_permitted_alphabet_5(const void *sptr) {
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv <= 127LL)) return -1;
	}
	return 0;
}

static int
memb_processMethod_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1LL && size <= 255LL)
		 && !check_permitted_alphabet_2(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_processAgency_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1LL && size <= 255LL)
		 && !check_permitted_alphabet_3(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_lastCheckedDate_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1LL && size <= 255LL)
		 && !check_permitted_alphabet_4(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_geoidUsed_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1LL && size <= 255LL)
		 && !check_permitted_alphabet_5(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_processMethod_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0l,  127l }	/* (0..127) */,
	{ APC_CONSTRAINED,	 8,  8,  1l,  255l }	/* (SIZE(1..255)) */,
	0, 0	/* No PER character map necessary */
};
static asn_per_constraints_t asn_PER_memb_processAgency_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0l,  127l }	/* (0..127) */,
	{ APC_CONSTRAINED,	 8,  8,  1l,  255l }	/* (SIZE(1..255)) */,
	0, 0	/* No PER character map necessary */
};
static asn_per_constraints_t asn_PER_memb_lastCheckedDate_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0l,  127l }	/* (0..127) */,
	{ APC_CONSTRAINED,	 8,  8,  1l,  255l }	/* (SIZE(1..255)) */,
	0, 0	/* No PER character map necessary */
};
static asn_per_constraints_t asn_PER_memb_geoidUsed_constr_5 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0l,  127l }	/* (0..127) */,
	{ APC_CONSTRAINED,	 8,  8,  1l,  255l }	/* (SIZE(1..255)) */,
	0, 0	/* No PER character map necessary */
};
static asn_TYPE_member_t asn_MBR_DataParameters_1[] = {
	{ ATF_POINTER, 4, offsetof(struct DataParameters, processMethod),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		memb_processMethod_constraint_1,
		&asn_PER_memb_processMethod_constr_2,
		0,
		"processMethod"
		},
	{ ATF_POINTER, 3, offsetof(struct DataParameters, processAgency),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		memb_processAgency_constraint_1,
		&asn_PER_memb_processAgency_constr_3,
		0,
		"processAgency"
		},
	{ ATF_POINTER, 2, offsetof(struct DataParameters, lastCheckedDate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		memb_lastCheckedDate_constraint_1,
		&asn_PER_memb_lastCheckedDate_constr_4,
		0,
		"lastCheckedDate"
		},
	{ ATF_POINTER, 1, offsetof(struct DataParameters, geoidUsed),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		memb_geoidUsed_constraint_1,
		&asn_PER_memb_geoidUsed_constr_5,
		0,
		"geoidUsed"
		},
};
static const int asn_MAP_DataParameters_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_DataParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DataParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* processMethod */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* processAgency */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* lastCheckedDate */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* geoidUsed */
};
static asn_SEQUENCE_specifics_t asn_SPC_DataParameters_specs_1 = {
	sizeof(struct DataParameters),
	offsetof(struct DataParameters, _asn_ctx),
	asn_MAP_DataParameters_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_DataParameters_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DataParameters = {
	"DataParameters",
	"DataParameters",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DataParameters_tags_1,
	sizeof(asn_DEF_DataParameters_tags_1)
		/sizeof(asn_DEF_DataParameters_tags_1[0]), /* 1 */
	asn_DEF_DataParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataParameters_tags_1)
		/sizeof(asn_DEF_DataParameters_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DataParameters_1,
	4,	/* Elements count */
	&asn_SPC_DataParameters_specs_1	/* Additional specs */
};

