//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "RequestImportanceLevel.h"

int
RequestImportanceLevel_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
RequestImportanceLevel_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	td->aper_decoder   = asn_DEF_NativeEnumerated.aper_decoder;
	td->aper_encoder   = asn_DEF_NativeEnumerated.aper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
RequestImportanceLevel_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
RequestImportanceLevel_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
RequestImportanceLevel_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
RequestImportanceLevel_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
RequestImportanceLevel_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
RequestImportanceLevel_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
RequestImportanceLevel_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
RequestImportanceLevel_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

asn_enc_rval_t
RequestImportanceLevel_encode_aper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->aper_encoder(td, constraints, structure, per_out);
}

asn_dec_rval_t
RequestImportanceLevel_decode_aper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	RequestImportanceLevel_1_inherit_TYPE_descriptor(td);
	return td->aper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_per_constraints_t asn_PER_type_RequestImportanceLevel_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0l,  15l }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_RequestImportanceLevel_value2enum_1[] = {
	{ 0,	29,	"requestImportanceLevelUnKnown" },
	{ 1,	23,	"requestImportanceLevel1" },
	{ 2,	23,	"requestImportanceLevel2" },
	{ 3,	23,	"requestImportanceLevel3" },
	{ 4,	23,	"requestImportanceLevel4" },
	{ 5,	23,	"requestImportanceLevel5" },
	{ 6,	23,	"requestImportanceLevel6" },
	{ 7,	23,	"requestImportanceLevel7" },
	{ 8,	23,	"requestImportanceLevel8" },
	{ 9,	23,	"requestImportanceLevel9" },
	{ 10,	24,	"requestImportanceLevel10" },
	{ 11,	24,	"requestImportanceLevel11" },
	{ 12,	24,	"requestImportanceLevel12" },
	{ 13,	24,	"requestImportanceLevel13" },
	{ 14,	24,	"requestImportanceLevel14" },
	{ 15,	25,	"requestImportanceReserved" }
};
static const unsigned int asn_MAP_RequestImportanceLevel_enum2value_1[] = {
	1,	/* requestImportanceLevel1(1) */
	10,	/* requestImportanceLevel10(10) */
	11,	/* requestImportanceLevel11(11) */
	12,	/* requestImportanceLevel12(12) */
	13,	/* requestImportanceLevel13(13) */
	14,	/* requestImportanceLevel14(14) */
	2,	/* requestImportanceLevel2(2) */
	3,	/* requestImportanceLevel3(3) */
	4,	/* requestImportanceLevel4(4) */
	5,	/* requestImportanceLevel5(5) */
	6,	/* requestImportanceLevel6(6) */
	7,	/* requestImportanceLevel7(7) */
	8,	/* requestImportanceLevel8(8) */
	9,	/* requestImportanceLevel9(9) */
	0,	/* requestImportanceLevelUnKnown(0) */
	15	/* requestImportanceReserved(15) */
};
static const asn_INTEGER_specifics_t asn_SPC_RequestImportanceLevel_specs_1 = {
	asn_MAP_RequestImportanceLevel_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_RequestImportanceLevel_enum2value_1,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_RequestImportanceLevel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RequestImportanceLevel = {
	"RequestImportanceLevel",
	"RequestImportanceLevel",
	RequestImportanceLevel_free,
	RequestImportanceLevel_print,
	RequestImportanceLevel_constraint,
	RequestImportanceLevel_decode_ber,
	RequestImportanceLevel_encode_der,
	RequestImportanceLevel_decode_xer,
	RequestImportanceLevel_encode_xer,
	RequestImportanceLevel_decode_uper,
	RequestImportanceLevel_encode_uper,
	RequestImportanceLevel_decode_aper,
	RequestImportanceLevel_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RequestImportanceLevel_tags_1,
	sizeof(asn_DEF_RequestImportanceLevel_tags_1)
		/sizeof(asn_DEF_RequestImportanceLevel_tags_1[0]), /* 1 */
	asn_DEF_RequestImportanceLevel_tags_1,	/* Same as above */
	sizeof(asn_DEF_RequestImportanceLevel_tags_1)
		/sizeof(asn_DEF_RequestImportanceLevel_tags_1[0]), /* 1 */
	&asn_PER_type_RequestImportanceLevel_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_RequestImportanceLevel_specs_1	/* Additional specs */
};

