//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_AntiLockBrakeStatus_H_
#define	_AntiLockBrakeStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AntiLockBrakeStatus {
	AntiLockBrakeStatus_unavailable	= 0,
	AntiLockBrakeStatus_off	= 1,
	AntiLockBrakeStatus_on	= 2,
	AntiLockBrakeStatus_engaged	= 3
} e_AntiLockBrakeStatus;

/* AntiLockBrakeStatus */
typedef long	 AntiLockBrakeStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AntiLockBrakeStatus;
asn_struct_free_f AntiLockBrakeStatus_free;
asn_struct_print_f AntiLockBrakeStatus_print;
asn_constr_check_f AntiLockBrakeStatus_constraint;
ber_type_decoder_f AntiLockBrakeStatus_decode_ber;
der_type_encoder_f AntiLockBrakeStatus_encode_der;
xer_type_decoder_f AntiLockBrakeStatus_decode_xer;
xer_type_encoder_f AntiLockBrakeStatus_encode_xer;
per_type_decoder_f AntiLockBrakeStatus_decode_uper;
per_type_encoder_f AntiLockBrakeStatus_encode_uper;
per_type_decoder_f AntiLockBrakeStatus_decode_aper;
per_type_encoder_f AntiLockBrakeStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AntiLockBrakeStatus_H_ */
#include <asn_internal.h>
