//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_BrakeSystemStatus_H_
#define	_BrakeSystemStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BrakeAppliedStatus.h"
#include "TractionControlStatus.h"
#include "AntiLockBrakeStatus.h"
#include "StabilityControlStatus.h"
#include "BrakeBoostApplied.h"
#include "AuxiliaryBrakeStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BrakeSystemStatus */
typedef struct BrakeSystemStatus {
	BrakeAppliedStatus_t	 wheelBrakes;
	TractionControlStatus_t	 traction;
	AntiLockBrakeStatus_t	 abs;
	StabilityControlStatus_t	 scs;
	BrakeBoostApplied_t	 brakeBoost;
	AuxiliaryBrakeStatus_t	 auxBrakes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BrakeSystemStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BrakeSystemStatus;

#ifdef __cplusplus
}
#endif

#endif	/* _BrakeSystemStatus_H_ */
#include <asn_internal.h>
