//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_BrakeAppliedPressure_H_
#define	_BrakeAppliedPressure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BrakeAppliedPressure {
	BrakeAppliedPressure_unavailable	= 0,
	BrakeAppliedPressure_minPressure	= 1,
	BrakeAppliedPressure_bkLvl_2	= 2,
	BrakeAppliedPressure_bkLvl_3	= 3,
	BrakeAppliedPressure_bkLvl_4	= 4,
	BrakeAppliedPressure_bkLvl_5	= 5,
	BrakeAppliedPressure_bkLvl_6	= 6,
	BrakeAppliedPressure_bkLvl_7	= 7,
	BrakeAppliedPressure_bkLvl_8	= 8,
	BrakeAppliedPressure_bkLvl_9	= 9,
	BrakeAppliedPressure_bkLvl_10	= 10,
	BrakeAppliedPressure_bkLvl_11	= 11,
	BrakeAppliedPressure_bkLvl_12	= 12,
	BrakeAppliedPressure_bkLvl_13	= 13,
	BrakeAppliedPressure_bkLvl_14	= 14,
	BrakeAppliedPressure_maxPressure	= 15
} e_BrakeAppliedPressure;

/* BrakeAppliedPressure */
typedef long	 BrakeAppliedPressure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BrakeAppliedPressure;
asn_struct_free_f BrakeAppliedPressure_free;
asn_struct_print_f BrakeAppliedPressure_print;
asn_constr_check_f BrakeAppliedPressure_constraint;
ber_type_decoder_f BrakeAppliedPressure_decode_ber;
der_type_encoder_f BrakeAppliedPressure_encode_der;
xer_type_decoder_f BrakeAppliedPressure_decode_xer;
xer_type_encoder_f BrakeAppliedPressure_encode_xer;
per_type_decoder_f BrakeAppliedPressure_decode_uper;
per_type_encoder_f BrakeAppliedPressure_encode_uper;
per_type_decoder_f BrakeAppliedPressure_decode_aper;
per_type_encoder_f BrakeAppliedPressure_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BrakeAppliedPressure_H_ */
#include <asn_internal.h>
