//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_IntersectionState_H_
#define	_IntersectionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "IntersectionReferenceID.h"
#include "MsgCount.h"
#include "IntersectionStatusObject.h"
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "MovementList.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EnabledLaneList;
struct ManeuverAssistList;
struct RegionalExtension;

/* IntersectionState */
typedef struct IntersectionState {
	DescriptiveName_t	*name	/* OPTIONAL */;
	IntersectionReferenceID_t	 id;
	MsgCount_t	 revision;
	IntersectionStatusObject_t	 status;
	MinuteOfTheYear_t	*moy	/* OPTIONAL */;
	DSecond_t	*timeStamp	/* OPTIONAL */;
	struct EnabledLaneList	*enabledLanes	/* OPTIONAL */;
	MovementList_t	 states;
	struct ManeuverAssistList	*maneuverAssistList	/* OPTIONAL */;
	struct IntersectionState__regional {
		A_SEQUENCE_OF(struct RegionalExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionState;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EnabledLaneList.h"
#include "ManeuverAssistList.h"
#include "RegionalExtension.h"

#endif	/* _IntersectionState_H_ */
#include <asn_internal.h>
