//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_IntersectionGeometry_H_
#define	_IntersectionGeometry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "IntersectionReferenceID.h"
#include "MsgCount.h"
#include "Position3D.h"
#include "LaneWidth.h"
#include "LaneList.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitList;
struct PreemptPriorityList;
struct RegionalExtension;

/* IntersectionGeometry */
typedef struct IntersectionGeometry {
	DescriptiveName_t	*name	/* OPTIONAL */;
	IntersectionReferenceID_t	 id;
	MsgCount_t	 revision;
	Position3D_t	 refPoint;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	struct SpeedLimitList	*speedLimits	/* OPTIONAL */;
	LaneList_t	 laneSet;
	struct PreemptPriorityList	*preemptPriorityData	/* OPTIONAL */;
	struct IntersectionGeometry__regional {
		A_SEQUENCE_OF(struct RegionalExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionGeometry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionGeometry;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitList.h"
#include "PreemptPriorityList.h"
#include "RegionalExtension.h"

#endif	/* _IntersectionGeometry_H_ */
#include <asn_internal.h>
