//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ITISCodesChoice_H_
#define	_ITISCodesChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ITIScodes.h"
#include "ITIStextPhrase.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITISCodesChoice__item_PR {
	ITISCodesChoice__item_PR_NOTHING,	/* No components present */
	ITISCodesChoice__item_PR_itis,
	ITISCodesChoice__item_PR_text
} ITISCodesChoice__item_PR;

/* ITISCodesChoice */
typedef struct ITISCodesChoice {
	struct ITISCodesChoice__item {
		ITISCodesChoice__item_PR present;
		union ITISCodesChoice__item_u {
			ITIScodes_t	 itis;
			ITIStextPhrase_t	 text;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} item;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITISCodesChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITISCodesChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _ITISCodesChoice_H_ */
#include <asn_internal.h>
