//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_LaneDirection_H_
#define	_LaneDirection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LaneDirection {
	LaneDirection_ingressPath	= 0,
	LaneDirection_egressPath	= 1
} e_LaneDirection;

/* LaneDirection */
typedef BIT_STRING_t	 LaneDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneDirection;
asn_struct_free_f LaneDirection_free;
asn_struct_print_f LaneDirection_print;
asn_constr_check_f LaneDirection_constraint;
ber_type_decoder_f LaneDirection_decode_ber;
der_type_encoder_f LaneDirection_encode_der;
xer_type_decoder_f LaneDirection_decode_xer;
xer_type_encoder_f LaneDirection_encode_xer;
per_type_decoder_f LaneDirection_decode_uper;
per_type_encoder_f LaneDirection_encode_uper;
per_type_decoder_f LaneDirection_decode_aper;
per_type_encoder_f LaneDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneDirection_H_ */
#include <asn_internal.h>
