//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_MotorizedPropelledType_H_
#define	_MotorizedPropelledType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MotorizedPropelledType {
	MotorizedPropelledType_unavailable	= 0,
	MotorizedPropelledType_otherTypes	= 1,
	MotorizedPropelledType_wheelChair	= 2,
	MotorizedPropelledType_bicycle	= 3,
	MotorizedPropelledType_scooter	= 4,
	MotorizedPropelledType_selfBalancingDevice	= 5
	/*
	 * Enumeration is extensible
	 */
} e_MotorizedPropelledType;

/* MotorizedPropelledType */
typedef long	 MotorizedPropelledType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MotorizedPropelledType;
asn_struct_free_f MotorizedPropelledType_free;
asn_struct_print_f MotorizedPropelledType_print;
asn_constr_check_f MotorizedPropelledType_constraint;
ber_type_decoder_f MotorizedPropelledType_decode_ber;
der_type_encoder_f MotorizedPropelledType_encode_der;
xer_type_decoder_f MotorizedPropelledType_decode_xer;
xer_type_encoder_f MotorizedPropelledType_encode_xer;
per_type_decoder_f MotorizedPropelledType_decode_uper;
per_type_encoder_f MotorizedPropelledType_encode_uper;
per_type_decoder_f MotorizedPropelledType_decode_aper;
per_type_encoder_f MotorizedPropelledType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MotorizedPropelledType_H_ */
#include <asn_internal.h>
