//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_NMEA_Revision_H_
#define	_NMEA_Revision_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NMEA_Revision {
	NMEA_Revision_unknown	= 0,
	NMEA_Revision_reserved	= 1,
	NMEA_Revision_rev1	= 2,
	NMEA_Revision_rev2	= 3,
	NMEA_Revision_rev3	= 4,
	NMEA_Revision_rev4	= 5,
	NMEA_Revision_rev5	= 6
	/*
	 * Enumeration is extensible
	 */
} e_NMEA_Revision;

/* NMEA-Revision */
typedef long	 NMEA_Revision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NMEA_Revision;
asn_struct_free_f NMEA_Revision_free;
asn_struct_print_f NMEA_Revision_print;
asn_constr_check_f NMEA_Revision_constraint;
ber_type_decoder_f NMEA_Revision_decode_ber;
der_type_encoder_f NMEA_Revision_encode_der;
xer_type_decoder_f NMEA_Revision_decode_xer;
xer_type_encoder_f NMEA_Revision_encode_xer;
per_type_decoder_f NMEA_Revision_decode_uper;
per_type_encoder_f NMEA_Revision_encode_uper;
per_type_decoder_f NMEA_Revision_decode_aper;
per_type_encoder_f NMEA_Revision_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NMEA_Revision_H_ */
#include <asn_internal.h>
