//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_NodeOffsetPointLL_H_
#define	_NodeOffsetPointLL_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Node-LL-24B.h"
#include "Node-LL-28B.h"
#include "Node-LL-32B.h"
#include "Node-LL-36B.h"
#include "Node-LL-44B.h"
#include "Node-LL-48B.h"
#include "Node-LLmD-64b.h"
#include "RegionalExtension.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeOffsetPointLL_PR {
	NodeOffsetPointLL_PR_NOTHING,	/* No components present */
	NodeOffsetPointLL_PR_node_LL1,
	NodeOffsetPointLL_PR_node_LL2,
	NodeOffsetPointLL_PR_node_LL3,
	NodeOffsetPointLL_PR_node_LL4,
	NodeOffsetPointLL_PR_node_LL5,
	NodeOffsetPointLL_PR_node_LL6,
	NodeOffsetPointLL_PR_node_LatLon,
	NodeOffsetPointLL_PR_regional
} NodeOffsetPointLL_PR;

/* NodeOffsetPointLL */
typedef struct NodeOffsetPointLL {
	NodeOffsetPointLL_PR present;
	union NodeOffsetPointLL_u {
		Node_LL_24B_t	 node_LL1;
		Node_LL_28B_t	 node_LL2;
		Node_LL_32B_t	 node_LL3;
		Node_LL_36B_t	 node_LL4;
		Node_LL_44B_t	 node_LL5;
		Node_LL_48B_t	 node_LL6;
		Node_LLmD_64b_t	 node_LatLon;
		RegionalExtension_92P46_t	 regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeOffsetPointLL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeOffsetPointLL;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeOffsetPointLL_H_ */
#include <asn_internal.h>
