//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_PersonalDeviceUserType_H_
#define	_PersonalDeviceUserType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PersonalDeviceUserType {
	PersonalDeviceUserType_unavailable	= 0,
	PersonalDeviceUserType_aPEDESTRIAN	= 1,
	PersonalDeviceUserType_aPEDALCYCLIST	= 2,
	PersonalDeviceUserType_aPUBLICSAFETYWORKER	= 3,
	PersonalDeviceUserType_anANIMAL	= 4
	/*
	 * Enumeration is extensible
	 */
} e_PersonalDeviceUserType;

/* PersonalDeviceUserType */
typedef long	 PersonalDeviceUserType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PersonalDeviceUserType;
asn_struct_free_f PersonalDeviceUserType_free;
asn_struct_print_f PersonalDeviceUserType_print;
asn_constr_check_f PersonalDeviceUserType_constraint;
ber_type_decoder_f PersonalDeviceUserType_decode_ber;
der_type_encoder_f PersonalDeviceUserType_encode_der;
xer_type_decoder_f PersonalDeviceUserType_decode_xer;
xer_type_encoder_f PersonalDeviceUserType_encode_xer;
per_type_decoder_f PersonalDeviceUserType_decode_uper;
per_type_encoder_f PersonalDeviceUserType_encode_uper;
per_type_decoder_f PersonalDeviceUserType_decode_aper;
per_type_encoder_f PersonalDeviceUserType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonalDeviceUserType_H_ */
#include <asn_internal.h>
