//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_PrivilegedEventFlags_H_
#define	_PrivilegedEventFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrivilegedEventFlags {
	PrivilegedEventFlags_peUnavailable	= 0,
	PrivilegedEventFlags_peEmergencyResponse	= 1,
	PrivilegedEventFlags_peEmergencyLightsActive	= 2,
	PrivilegedEventFlags_peEmergencySoundActive	= 3,
	PrivilegedEventFlags_peNonEmergencyLightsActive	= 4,
	PrivilegedEventFlags_peNonEmergencySoundActive	= 5
} e_PrivilegedEventFlags;

/* PrivilegedEventFlags */
typedef BIT_STRING_t	 PrivilegedEventFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivilegedEventFlags;
asn_struct_free_f PrivilegedEventFlags_free;
asn_struct_print_f PrivilegedEventFlags_print;
asn_constr_check_f PrivilegedEventFlags_constraint;
ber_type_decoder_f PrivilegedEventFlags_decode_ber;
der_type_encoder_f PrivilegedEventFlags_encode_der;
xer_type_decoder_f PrivilegedEventFlags_decode_xer;
xer_type_encoder_f PrivilegedEventFlags_encode_xer;
per_type_decoder_f PrivilegedEventFlags_decode_uper;
per_type_encoder_f PrivilegedEventFlags_encode_uper;
per_type_decoder_f PrivilegedEventFlags_decode_aper;
per_type_encoder_f PrivilegedEventFlags_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PrivilegedEventFlags_H_ */
#include <asn_internal.h>
