//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RainSensor_H_
#define	_RainSensor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RainSensor {
	RainSensor_none	= 0,
	RainSensor_lightMist	= 1,
	RainSensor_heavyMist	= 2,
	RainSensor_lightRainOrDrizzle	= 3,
	RainSensor_rain	= 4,
	RainSensor_moderateRain	= 5,
	RainSensor_heavyRain	= 6,
	RainSensor_heavyDownpour	= 7
} e_RainSensor;

/* RainSensor */
typedef long	 RainSensor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RainSensor;
asn_struct_free_f RainSensor_free;
asn_struct_print_f RainSensor_print;
asn_constr_check_f RainSensor_constraint;
ber_type_decoder_f RainSensor_decode_ber;
der_type_encoder_f RainSensor_encode_der;
xer_type_decoder_f RainSensor_decode_xer;
xer_type_encoder_f RainSensor_encode_xer;
per_type_decoder_f RainSensor_decode_uper;
per_type_encoder_f RainSensor_encode_uper;
per_type_decoder_f RainSensor_decode_aper;
per_type_encoder_f RainSensor_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RainSensor_H_ */
#include <asn_internal.h>
