//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RegionOffsets_H_
#define	_RegionOffsets_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OffsetLL-B16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RegionOffsets */
typedef struct RegionOffsets {
	OffsetLL_B16_t	 xOffset;
	OffsetLL_B16_t	 yOffset;
	OffsetLL_B16_t	*zOffset	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionOffsets_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionOffsets;

#ifdef __cplusplus
}
#endif

#endif	/* _RegionOffsets_H_ */
#include <asn_internal.h>
