//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RegionalExtension_H_
#define	_RegionalExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RegionId.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RegionalExtension */
typedef struct RegionalExtension_92P0 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P0_t;
typedef struct RegionalExtension_92P1 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P1_t;
typedef struct RegionalExtension_92P2 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P2_t;
typedef struct RegionalExtension_92P3 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P3_t;
typedef struct RegionalExtension_92P4 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P4_t;
typedef struct RegionalExtension_92P5 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P5_t;
typedef struct RegionalExtension_92P6 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P6_t;
typedef struct RegionalExtension_92P7 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P7_t;
typedef struct RegionalExtension_92P8 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P8_t;
typedef struct RegionalExtension_92P9 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P9_t;
typedef struct RegionalExtension_92P10 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P10_t;
typedef struct RegionalExtension_92P11 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P11_t;
typedef struct RegionalExtension_92P12 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P12_t;
typedef struct RegionalExtension_92P13 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P13_t;
typedef struct RegionalExtension_92P14 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P14_t;
typedef struct RegionalExtension_92P15 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P15_t;
typedef struct RegionalExtension_92P16 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P16_t;
typedef struct RegionalExtension_92P17 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P17_t;
typedef struct RegionalExtension_92P18 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P18_t;
typedef struct RegionalExtension_92P19 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P19_t;
typedef struct RegionalExtension_92P20 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P20_t;
typedef struct RegionalExtension_92P21 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P21_t;
typedef struct RegionalExtension_92P22 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P22_t;
typedef struct RegionalExtension_92P23 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P23_t;
typedef struct RegionalExtension_92P24 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P24_t;
typedef struct RegionalExtension_92P25 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P25_t;
typedef struct RegionalExtension_92P26 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P26_t;
typedef struct RegionalExtension_92P27 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P27_t;
typedef struct RegionalExtension_92P28 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P28_t;
typedef struct RegionalExtension_92P29 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P29_t;
typedef struct RegionalExtension_92P30 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P30_t;
typedef struct RegionalExtension_92P31 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P31_t;
typedef struct RegionalExtension_92P32 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P32_t;
typedef struct RegionalExtension_92P33 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P33_t;
typedef struct RegionalExtension_92P34 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P34_t;
typedef struct RegionalExtension_92P35 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P35_t;
typedef struct RegionalExtension_92P36 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P36_t;
typedef struct RegionalExtension_92P37 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P37_t;
typedef struct RegionalExtension_92P38 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P38_t;
typedef struct RegionalExtension_92P39 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P39_t;
typedef struct RegionalExtension_92P40 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P40_t;
typedef struct RegionalExtension_92P41 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P41_t;
typedef struct RegionalExtension_92P42 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P42_t;
typedef struct RegionalExtension_92P43 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P43_t;
typedef struct RegionalExtension_92P44 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P44_t;
typedef struct RegionalExtension_92P45 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P45_t;
typedef struct RegionalExtension_92P46 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P46_t;
typedef struct RegionalExtension_92P47 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P47_t;
typedef struct RegionalExtension_92P48 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P48_t;
typedef struct RegionalExtension_92P49 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P49_t;
typedef struct RegionalExtension_92P50 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P50_t;
typedef struct RegionalExtension_92P51 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P51_t;
typedef struct RegionalExtension_92P52 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P52_t;
typedef struct RegionalExtension_92P53 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P53_t;
typedef struct RegionalExtension_92P54 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P54_t;
typedef struct RegionalExtension_92P55 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P55_t;
typedef struct RegionalExtension_92P56 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P56_t;
typedef struct RegionalExtension_92P57 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P57_t;
typedef struct RegionalExtension_92P58 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P58_t;
typedef struct RegionalExtension_92P59 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P59_t;
typedef struct RegionalExtension_92P60 {
	RegionId_t	 regionId;
	ANY_t	 regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionalExtension_92P60_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P0;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P1;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P2;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P3;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P4;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P5;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P6;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P7;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P8;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P9;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P10;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P11;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P12;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P13;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P14;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P15;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P16;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P17;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P18;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P19;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P20;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P21;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P22;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P23;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P24;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P25;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P26;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P27;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P28;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P29;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P30;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P31;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P32;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P33;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P34;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P35;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P36;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P37;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P38;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P39;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P40;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P41;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P42;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P43;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P44;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P45;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P46;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P47;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P48;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P49;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P50;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P51;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P52;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P53;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P54;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P55;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P56;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P57;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P58;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P59;
extern asn_TYPE_descriptor_t asn_DEF_RegionalExtension_92P60;

#ifdef __cplusplus
}
#endif

#endif	/* _RegionalExtension_H_ */
#include <asn_internal.h>
