//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RequestorDescription_H_
#define	_RequestorDescription_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleID.h"
#include "DescriptiveName.h"
#include "TransitVehicleStatus.h"
#include "TransitVehicleOccupancy.h"
#include "DeltaTime.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RequestorType;
struct RequestorPositionVector;
struct RegionalExtension;

/* RequestorDescription */
typedef struct RequestorDescription {
	VehicleID_t	 id;
	struct RequestorType	*type	/* OPTIONAL */;
	struct RequestorPositionVector	*position	/* OPTIONAL */;
	DescriptiveName_t	*name	/* OPTIONAL */;
	DescriptiveName_t	*routeName	/* OPTIONAL */;
	TransitVehicleStatus_t	*transitStatus	/* OPTIONAL */;
	TransitVehicleOccupancy_t	*transitOccupancy	/* OPTIONAL */;
	DeltaTime_t	*transitSchedule	/* OPTIONAL */;
	struct RequestorDescription__regional {
		A_SEQUENCE_OF(struct RegionalExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RequestorDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestorDescription;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RequestorType.h"
#include "RequestorPositionVector.h"
#include "RegionalExtension.h"

#endif	/* _RequestorDescription_H_ */
#include <asn_internal.h>
