//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ResponseType_H_
#define	_ResponseType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResponseType {
	ResponseType_notInUseOrNotEquipped	= 0,
	ResponseType_emergency	= 1,
	ResponseType_nonEmergency	= 2,
	ResponseType_pursuit	= 3,
	ResponseType_stationary	= 4,
	ResponseType_slowMoving	= 5,
	ResponseType_stopAndGoMovement	= 6
	/*
	 * Enumeration is extensible
	 */
} e_ResponseType;

/* ResponseType */
typedef long	 ResponseType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResponseType;
asn_struct_free_f ResponseType_free;
asn_struct_print_f ResponseType_print;
asn_constr_check_f ResponseType_constraint;
ber_type_decoder_f ResponseType_decode_ber;
der_type_encoder_f ResponseType_encode_der;
xer_type_decoder_f ResponseType_decode_xer;
xer_type_encoder_f ResponseType_encode_xer;
per_type_decoder_f ResponseType_decode_uper;
per_type_encoder_f ResponseType_encode_uper;
per_type_decoder_f ResponseType_decode_aper;
per_type_encoder_f ResponseType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResponseType_H_ */
#include <asn_internal.h>
