//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_TransitVehicleStatus_H_
#define	_TransitVehicleStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransitVehicleStatus {
	TransitVehicleStatus_loading	= 0,
	TransitVehicleStatus_anADAuse	= 1,
	TransitVehicleStatus_aBikeLoad	= 2,
	TransitVehicleStatus_doorOpen	= 3,
	TransitVehicleStatus_charging	= 4,
	TransitVehicleStatus_atStopLine	= 5
} e_TransitVehicleStatus;

/* TransitVehicleStatus */
typedef BIT_STRING_t	 TransitVehicleStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransitVehicleStatus;
asn_struct_free_f TransitVehicleStatus_free;
asn_struct_print_f TransitVehicleStatus_print;
asn_constr_check_f TransitVehicleStatus_constraint;
ber_type_decoder_f TransitVehicleStatus_decode_ber;
der_type_encoder_f TransitVehicleStatus_encode_der;
xer_type_decoder_f TransitVehicleStatus_decode_xer;
xer_type_encoder_f TransitVehicleStatus_encode_xer;
per_type_decoder_f TransitVehicleStatus_decode_uper;
per_type_encoder_f TransitVehicleStatus_encode_uper;
per_type_decoder_f TransitVehicleStatus_decode_aper;
per_type_encoder_f TransitVehicleStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TransitVehicleStatus_H_ */
#include <asn_internal.h>
