//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_TransitStatus_H_
#define	_TransitStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransitStatus {
	TransitStatus_none	= 0,
	TransitStatus_anADAuse	= 1,
	TransitStatus_aBikeLoad	= 2,
	TransitStatus_doorOpen	= 3,
	TransitStatus_occM	= 4,
	TransitStatus_occL	= 5
} e_TransitStatus;

/* TransitStatus */
typedef BIT_STRING_t	 TransitStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransitStatus;
asn_struct_free_f TransitStatus_free;
asn_struct_print_f TransitStatus_print;
asn_constr_check_f TransitStatus_constraint;
ber_type_decoder_f TransitStatus_decode_ber;
der_type_encoder_f TransitStatus_encode_der;
xer_type_decoder_f TransitStatus_decode_xer;
xer_type_encoder_f TransitStatus_encode_xer;
per_type_decoder_f TransitStatus_decode_uper;
per_type_encoder_f TransitStatus_encode_uper;
per_type_decoder_f TransitStatus_decode_aper;
per_type_encoder_f TransitStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TransitStatus_H_ */
#include <asn_internal.h>
