//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_URL_Base_H_
#define	_URL_Base_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* URL-Base */
typedef IA5String_t	 URL_Base_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_URL_Base;
asn_struct_free_f URL_Base_free;
asn_struct_print_f URL_Base_print;
asn_constr_check_f URL_Base_constraint;
ber_type_decoder_f URL_Base_decode_ber;
der_type_encoder_f URL_Base_encode_der;
xer_type_decoder_f URL_Base_decode_xer;
xer_type_encoder_f URL_Base_encode_xer;
per_type_decoder_f URL_Base_decode_uper;
per_type_encoder_f URL_Base_encode_uper;
per_type_decoder_f URL_Base_decode_aper;
per_type_encoder_f URL_Base_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _URL_Base_H_ */
#include <asn_internal.h>
