//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_VehicleID_H_
#define	_VehicleID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TemporaryID.h"
#include "StationID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleID_PR {
	VehicleID_PR_NOTHING,	/* No components present */
	VehicleID_PR_entityID,
	VehicleID_PR_stationID
} VehicleID_PR;

/* VehicleID */
typedef struct VehicleID {
	VehicleID_PR present;
	union VehicleID_u {
		TemporaryID_t	 entityID;
		StationID_t	 stationID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleID;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleID_H_ */
#include <asn_internal.h>
