//********************************************************************************************************
//
// © 2016 Regents of the University of California on behalf of the University of California at Berkeley
//       with rights granted for USDOT OSADP distribution with the ECL-2.0 open source license.
//
//*********************************************************************************************************
/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../j2735_asn/J2735_201601_ASN_mmitss.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_WheelSensorStatus_H_
#define	_WheelSensorStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WheelSensorStatus {
	WheelSensorStatus_off	= 0,
	WheelSensorStatus_on	= 1,
	WheelSensorStatus_notDefined	= 2,
	WheelSensorStatus_notSupported	= 3
} e_WheelSensorStatus;

/* WheelSensorStatus */
typedef long	 WheelSensorStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WheelSensorStatus;
asn_struct_free_f WheelSensorStatus_free;
asn_struct_print_f WheelSensorStatus_print;
asn_constr_check_f WheelSensorStatus_constraint;
ber_type_decoder_f WheelSensorStatus_decode_ber;
der_type_encoder_f WheelSensorStatus_encode_der;
xer_type_decoder_f WheelSensorStatus_decode_xer;
xer_type_encoder_f WheelSensorStatus_encode_xer;
per_type_decoder_f WheelSensorStatus_decode_uper;
per_type_encoder_f WheelSensorStatus_encode_uper;
per_type_decoder_f WheelSensorStatus_decode_aper;
per_type_encoder_f WheelSensorStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _WheelSensorStatus_H_ */
#include <asn_internal.h>
